package tech.gmork.model.enums;

public enum DeploymentStrategy {
    COMPLETE_ALL_AT_ONCE,
    PARTIAL_BY_PERCENTAGE,
    PARTIAL_BY_QUANTITY,
    PARTIAL_BY_USER_DEFINED_HOST_IDS,
    COMPLETE_GRADUAL_BY_PERCENTAGE,
    COMPLETE_GRADUAL_BY_QUANTITY
}
